"""
build_micro_panel_config.py – Build microbiology panel configuration.

Writes the canonical micro_panel_config.yaml to CLASSIFICATIONS_DIR.
The configuration is derived from EDA on microbiologyevents in MIMIC-IV v3.1
and is hardcoded here — no external data source is required.

Output format:
    panels:
        <panel_name>:
            combos:
                - [test_name, spec_type_desc]
                ...
    excluded_tests:
        - <test_name>
        ...
    excluded_spec_types:
        - <spec_type_desc>
        ...
    comment_cleaning:
        max_sentences: 2
        max_chars: 200
        discard_prefixes:
            - ...
        strip_triggers:
            - ...

Expected config keys:
    CLASSIFICATIONS_DIR – output directory for micro_panel_config.yaml
"""

import logging
import os

import yaml

from preprocessing_utils import _check_required_keys

logger = logging.getLogger(__name__)

PANELS_37 = {
    "blood_culture_routine": [
        ("AEROBIC BOTTLE", "BLOOD CULTURE"),
        ("ANAEROBIC BOTTLE", "BLOOD CULTURE"),
        ("BARTONELLA BLOOD CULTURE", "BLOOD CULTURE"),
        ("BLOOD/AFB CULTURE", "BLOOD CULTURE"),
        ("BLOOD/AFB CULTURE", "BLOOD CULTURE ( MYCO/F LYTIC BOTTLE)"),
        ("BLOOD/FUNGAL CULTURE", "BLOOD CULTURE"),
        ("BLOOD/FUNGAL CULTURE", "BLOOD CULTURE ( MYCO/F LYTIC BOTTLE)"),
        ("BRUCELLA BLOOD CULTURE", "BLOOD CULTURE"),
        ("Blood Culture, Neonate", "BLOOD CULTURE - NEONATE"),
        ("Blood Culture, Routine", "BLOOD CULTURE"),
        ("ISOLATE FOR MIC", "BLOOD CULTURE"),
        ("ISOLATE FOR MIC", "Isolate"),
        ("M. furfur Blood Culture", "BLOOD CULTURE"),
        ("M.FURFUR CULTURE", "BLOOD CULTURE"),
    ],
    "blood_bottle_gram_stain": [
        ("AEROBIC BOTTLE", "FLUID RECEIVED IN BLOOD CULTURE BOTTLES"),
        ("ANAEROBIC BOTTLE", "FLUID RECEIVED IN BLOOD CULTURE BOTTLES"),
        ("Aerobic Bottle Gram Stain", "BLOOD CULTURE"),
        ("Aerobic Bottle Gram Stain", "FLUID RECEIVED IN BLOOD CULTURE BOTTLES"),
        ("Anaerobic Bottle Gram Stain", "BLOOD CULTURE"),
        ("Anaerobic Bottle Gram Stain", "FLUID RECEIVED IN BLOOD CULTURE BOTTLES"),
        ("Fluid Culture in Bottles", "FLUID RECEIVED IN BLOOD CULTURE BOTTLES"),
        ("Myco-F Bottle Gram Stain", "BLOOD CULTURE ( MYCO/F LYTIC BOTTLE)"),
        ("Pediatric Bottle Gram Stain", "Isolate"),
        ("STEM CELL - AEROBIC BOTTLE", "Stem Cell - Blood Culture"),
        ("STEM CELL - ANAEROBIC BOTTLE", "Stem Cell - Blood Culture"),
        ("Stem Cell Aer/Ana Culture", "Stem Cell - Blood Culture"),
        ("BLOOD/FUNGAL CULTURE", "FLUID RECEIVED IN BLOOD CULTURE BOTTLES"),
        ("BLOOD/AFB CULTURE", "FLUID RECEIVED IN BLOOD CULTURE BOTTLES"),
        ("Anaerobic Bottle Gram Stain", "Stem Cell - Blood Culture"),
    ],
    "urine_culture": [
        ("ANAEROBIC CULTURE", "URINE"),
        ("ANAEROBIC CULTURE", "URINE,KIDNEY"),
        ("FLUID CULTURE", "URINE"),
        ("FLUID CULTURE", "URINE,KIDNEY"),
        ("FLUID CULTURE", "URINE,SUPRAPUBIC ASPIRATE"),
        ("FUNGAL CULTURE", "URINE"),
        ("ISOLATE FOR MIC", "URINE"),
        ("REFLEX URINE CULTURE", "URINE"),
        ("URINE CULTURE", "URINE"),
        ("URINE CULTURE", "URINE,KIDNEY"),
        ("URINE CULTURE", "URINE,SUPRAPUBIC ASPIRATE"),
        ("URINE-GRAM STAIN - UNSPUN", "URINE"),
        ("URINE-GRAM STAIN - UNSPUN", "URINE,KIDNEY"),
    ],
    "urine_viral": [
        ("CYTOMEGALOVIRUS EARLY ANTIGEN TEST (SHELL VIAL METHOD)", "URINE"),
        ("VIRAL CULTURE", "URINE"),
        ("VIRAL CULTURE: R/O CYTOMEGALOVIRUS", "URINE"),
    ],
    "urinary_antigens": [
        ("Legionella Urinary Antigen", "URINE"),
    ],
    "respiratory_non_invasive": [
        ("ISOLATE FOR MIC", "SPUTUM"),
        ("RESPIRATORY CULTURE", "ASPIRATE"),
        ("RESPIRATORY CULTURE", "SPUTUM"),
    ],
    "respiratory_invasive": [
        ("ANAEROBIC CULTURE", "BRONCHOALVEOLAR LAVAGE"),
        ("FLUID CULTURE", "BRONCHIAL WASHINGS"),
        ("RESPIRATORY CULTURE", "BRONCHIAL BRUSH"),
        ("RESPIRATORY CULTURE", "BRONCHIAL BRUSH - PROTECTED"),
        ("RESPIRATORY CULTURE", "BRONCHIAL WASHINGS"),
        ("RESPIRATORY CULTURE", "BRONCHOALVEOLAR LAVAGE"),
        ("RESPIRATORY CULTURE", "Mini-BAL"),
        ("RESPIRATORY CULTURE", "TRACHEAL ASPIRATE"),
    ],
    "respiratory_afb": [
        ("ACID FAST CULTURE", "BRONCHIAL BRUSH"),
        ("ACID FAST CULTURE", "BRONCHIAL BRUSH - PROTECTED"),
        ("ACID FAST CULTURE", "BRONCHIAL WASHINGS"),
        ("ACID FAST CULTURE", "BRONCHOALVEOLAR LAVAGE"),
        ("ACID FAST CULTURE", "Mini-BAL"),
        ("ACID FAST CULTURE", "SPUTUM"),
        ("ACID FAST CULTURE", "TRACHEAL ASPIRATE"),
        ("ACID FAST SMEAR", "BRONCHIAL BRUSH"),
        ("ACID FAST SMEAR", "BRONCHIAL BRUSH - PROTECTED"),
        ("ACID FAST SMEAR", "BRONCHIAL WASHINGS"),
        ("ACID FAST SMEAR", "BRONCHOALVEOLAR LAVAGE"),
        ("ACID FAST SMEAR", "Mini-BAL"),
        ("ACID FAST SMEAR", "SPUTUM"),
        ("ACID FAST SMEAR", "TRACHEAL ASPIRATE"),
        ("GEN-PROBE AMPLIFIED M. TUBERCULOSIS DIRECT TEST (MTD)", "BRONCHOALVEOLAR LAVAGE"),
        ("GEN-PROBE AMPLIFIED M. TUBERCULOSIS DIRECT TEST (MTD)", "SPUTUM"),
        ("MODIFIED ACID-FAST STAIN FOR NOCARDIA", "BRONCHOALVEOLAR LAVAGE"),
        ("MODIFIED ACID-FAST STAIN FOR NOCARDIA", "SPUTUM"),
        ("MTB Direct Amplification", "BRONCHIAL WASHINGS"),
        ("MTB Direct Amplification", "BRONCHOALVEOLAR LAVAGE"),
        ("MTB Direct Amplification", "SPUTUM"),
        ("NOCARDIA CULTURE", "BRONCHOALVEOLAR LAVAGE"),
        ("NOCARDIA CULTURE", "Mini-BAL"),
        ("NOCARDIA CULTURE", "SPUTUM"),
    ],
    "respiratory_viral": [
        ("CYTOMEGALOVIRUS EARLY ANTIGEN TEST (SHELL VIAL METHOD)", "BRONCHIAL WASHINGS"),
        ("CYTOMEGALOVIRUS EARLY ANTIGEN TEST (SHELL VIAL METHOD)", "BRONCHOALVEOLAR LAVAGE"),
        ("CYTOMEGALOVIRUS EARLY ANTIGEN TEST (SHELL VIAL METHOD)", "Mini-BAL"),
        ("CYTOMEGALOVIRUS EARLY ANTIGEN TEST (SHELL VIAL METHOD)", "Rapid Respiratory Viral Screen & Culture"),
        ("DIRECT INFLUENZA A ANTIGEN TEST", "ASPIRATE"),
        ("DIRECT INFLUENZA A ANTIGEN TEST", "Influenza A/B by DFA"),
        ("DIRECT INFLUENZA A ANTIGEN TEST", "Influenza A/B by DFA - Bronch Lavage"),
        ("DIRECT INFLUENZA A ANTIGEN TEST", "RAPID RESPIRATORY VIRAL ANTIGEN TEST"),
        ("DIRECT INFLUENZA A ANTIGEN TEST", "SWAB"),
        ("DIRECT INFLUENZA B ANTIGEN TEST", "ASPIRATE"),
        ("DIRECT INFLUENZA B ANTIGEN TEST", "Influenza A/B by DFA"),
        ("DIRECT INFLUENZA B ANTIGEN TEST", "Influenza A/B by DFA - Bronch Lavage"),
        ("DIRECT INFLUENZA B ANTIGEN TEST", "RAPID RESPIRATORY VIRAL ANTIGEN TEST"),
        ("DIRECT INFLUENZA B ANTIGEN TEST", "Rapid Respiratory Viral Screen & Culture"),
        ("DIRECT INFLUENZA B ANTIGEN TEST", "SWAB"),
        ("DIRECT RSV ANTIGEN TEST", "Rapid Respiratory Viral Screen & Culture"),
        ("Respiratory Viral Antigen Screen", "ASPIRATE"),
        ("Respiratory Viral Antigen Screen", "BRONCHOALVEOLAR LAVAGE"),
        ("Respiratory Viral Antigen Screen", "Influenza A/B by DFA"),
        ("Respiratory Viral Antigen Screen", "RAPID RESPIRATORY VIRAL ANTIGEN TEST"),
        ("Respiratory Viral Antigen Screen", "Rapid Respiratory Viral Screen & Culture"),
        ("Respiratory Viral Antigen Screen", "SWAB"),
        ("Respiratory Viral Culture", "ASPIRATE"),
        ("Respiratory Viral Culture", "BRONCHOALVEOLAR LAVAGE"),
        ("Respiratory Viral Culture", "Influenza A/B by DFA"),
        ("Respiratory Viral Culture", "RAPID RESPIRATORY VIRAL ANTIGEN TEST"),
        ("Respiratory Viral Culture", "Rapid Respiratory Viral Screen & Culture"),
        ("Respiratory Viral Culture", "SWAB"),
        ("Respiratory Virus Identification", "ASPIRATE"),
        ("Respiratory Virus Identification", "Influenza A/B by DFA"),
        ("Respiratory Virus Identification", "RAPID RESPIRATORY VIRAL ANTIGEN TEST"),
        ("Respiratory Virus Identification", "Rapid Respiratory Viral Screen & Culture"),
        ("VARICELLA-ZOSTER CULTURE", "BRONCHOALVEOLAR LAVAGE"),
        ("VIRAL CULTURE", "BRONCHIAL WASHINGS"),
        ("VIRAL CULTURE", "BRONCHOALVEOLAR LAVAGE"),
        ("VIRAL CULTURE", "Influenza A/B by DFA"),
        ("VIRAL CULTURE", "RAPID RESPIRATORY VIRAL ANTIGEN TEST"),
        ("VIRAL CULTURE", "Rapid Respiratory Viral Screen & Culture"),
        ("VIRAL CULTURE", "SPUTUM"),
        ("VIRAL CULTURE: R/O CYTOMEGALOVIRUS", "BRONCHIAL WASHINGS"),
        ("VIRAL CULTURE: R/O CYTOMEGALOVIRUS", "BRONCHOALVEOLAR LAVAGE"),
        ("VIRAL CULTURE: R/O CYTOMEGALOVIRUS", "Mini-BAL"),
        ("VIRAL CULTURE: R/O CYTOMEGALOVIRUS", "Rapid Respiratory Viral Screen & Culture"),
        ("VIRAL CULTURE: R/O CYTOMEGALOVIRUS", "SPUTUM"),
        ("VIRAL CULTURE: R/O HERPES SIMPLEX VIRUS", "BRONCHOALVEOLAR LAVAGE"),
    ],
    "respiratory_pcp_legionella": [
        ("IMMUNOFLUORESCENT TEST FOR PNEUMOCYSTIS CARINII", "BRONCHOALVEOLAR LAVAGE"),
        ("IMMUNOFLUORESCENT TEST FOR PNEUMOCYSTIS CARINII", "SPUTUM"),
        ("Immunofluorescent test for Pneumocystis jirovecii (carinii)", "BRONCHIAL WASHINGS"),
        ("Immunofluorescent test for Pneumocystis jirovecii (carinii)", "BRONCHOALVEOLAR LAVAGE"),
        ("Immunofluorescent test for Pneumocystis jirovecii (carinii)", "Mini-BAL"),
        ("Immunofluorescent test for Pneumocystis jirovecii (carinii)", "SPUTUM"),
        ("Immunofluorescent test for Pneumocystis jirovecii (carinii)", "TISSUE"),
        ("LEGIONELLA CULTURE", "BRONCHIAL WASHINGS"),
        ("LEGIONELLA CULTURE", "BRONCHOALVEOLAR LAVAGE"),
        ("LEGIONELLA CULTURE", "Mini-BAL"),
        ("LEGIONELLA CULTURE", "PLEURAL FLUID"),
        ("LEGIONELLA CULTURE", "SPUTUM"),
        ("LEGIONELLA CULTURE", "SWAB"),
        ("LEGIONELLA CULTURE", "TISSUE"),
        ("NOCARDIA CULTURE", "BRONCHIAL BRUSH"),
        ("NOCARDIA CULTURE", "BRONCHIAL WASHINGS"),
        ("NOCARDIA CULTURE", "TRACHEAL ASPIRATE"),
    ],
    "gram_stain_respiratory": [
        ("GRAM STAIN", "BRONCHIAL BRUSH"),
        ("GRAM STAIN", "BRONCHIAL WASHINGS"),
        ("GRAM STAIN", "BRONCHOALVEOLAR LAVAGE"),
        ("GRAM STAIN", "Mini-BAL"),
        ("GRAM STAIN", "SPUTUM"),
        ("GRAM STAIN", "TRACHEAL ASPIRATE"),
    ],
    "gram_stain_wound_tissue": [
        ("GRAM STAIN", "ABSCESS"),
        ("GRAM STAIN", "ASPIRATE"),
        ("GRAM STAIN", "BILE"),
        ("GRAM STAIN", "BIOPSY"),
        ("GRAM STAIN", "DIALYSIS FLUID"),
        ("GRAM STAIN", "EAR"),
        ("GRAM STAIN", "FLUID WOUND"),
        ("GRAM STAIN", "FLUID,OTHER"),
        ("GRAM STAIN", "FOOT CULTURE"),
        ("GRAM STAIN", "STOOL"),
        ("GRAM STAIN", "SWAB"),
        ("GRAM STAIN", "TISSUE"),
        ("GRAM STAIN", "URINE"),
    ],
    "gram_stain_csf": [
        ("GRAM STAIN", "CSF;SPINAL FLUID"),
    ],
    "wound_culture": [
        ("ANAEROBIC CULTURE", "ABSCESS"),
        ("ANAEROBIC CULTURE", "ASPIRATE"),
        ("ANAEROBIC CULTURE", "BIOPSY"),
        ("ANAEROBIC CULTURE", "FLUID WOUND"),
        ("ANAEROBIC CULTURE", "FLUID,OTHER"),
        ("ANAEROBIC CULTURE", "FOOT CULTURE"),
        ("ANAEROBIC CULTURE", "SWAB"),
        ("ANAEROBIC CULTURE", "TISSUE"),
        ("FLUID CULTURE", "SWAB"),
        ("FLUID CULTURE", "TISSUE"),
        ("ISOLATE FOR MIC", "TISSUE"),
        ("MODIFIED ACID-FAST STAIN FOR NOCARDIA", "TISSUE"),
        ("NOCARDIA CULTURE", "ABSCESS"),
        ("NOCARDIA CULTURE", "SWAB"),
        ("NOCARDIA CULTURE", "TISSUE"),
        ("RESPIRATORY CULTURE", "EAR"),
        ("RESPIRATORY CULTURE", "EYE"),
        ("RESPIRATORY CULTURE", "FLUID,OTHER"),
        ("RESPIRATORY CULTURE", "SWAB"),
        ("RESPIRATORY CULTURE", "Staph aureus swab"),
        ("RESPIRATORY CULTURE", "THROAT CULTURE"),
        ("RESPIRATORY CULTURE", "THROAT FOR STREP"),
        ("TISSUE", "ABSCESS"),
        ("TISSUE", "BIOPSY"),
        ("TISSUE", "SWAB"),
        ("TISSUE", "TISSUE"),
        ("TISSUE CULTURE-TISSUE", "TISSUE"),
        ("WOUND CULTURE", "ABSCESS"),
        ("WOUND CULTURE", "ASPIRATE"),
        ("WOUND CULTURE", "CORNEAL EYE SCRAPINGS"),
        ("WOUND CULTURE", "FLUID WOUND"),
        ("WOUND CULTURE", "FLUID,OTHER"),
        ("WOUND CULTURE", "FOOT CULTURE"),
        ("WOUND CULTURE", "SWAB"),
        ("WOUND CULTURE", "TISSUE"),
    ],
    "hardware_and_lines_culture": [
        ("ACID FAST CULTURE", "FOREIGN BODY"),
        ("ACID FAST SMEAR", "FOREIGN BODY"),
        ("ANAEROBIC CULTURE", "FOREIGN BODY"),
        ("ANAEROBIC CULTURE", "Foreign Body - Sonication Culture"),
        ("FUNGAL CULTURE", "FOREIGN BODY"),
        ("GRAM STAIN", "CATHETER TIP-IV"),
        ("GRAM STAIN", "FLUID RECEIVED IN BLOOD CULTURE BOTTLES"),
        ("GRAM STAIN", "FOREIGN BODY"),
        ("POTASSIUM HYDROXIDE PREPARATION", "FOREIGN BODY"),
        ("Sonication culture, prosthetic joint", "FOREIGN BODY"),
        ("Sonication culture, prosthetic joint", "Foreign Body - Sonication Culture"),
        ("WOUND CULTURE", "CATHETER TIP-IV"),
        ("WOUND CULTURE", "FOREIGN BODY"),
    ],
    "pleural_culture": [
        ("ACID FAST CULTURE", "PLEURAL FLUID"),
        ("ACID FAST SMEAR", "PLEURAL FLUID"),
        ("ANAEROBIC CULTURE", "PLEURAL FLUID"),
        ("FLUID CULTURE", "PLEURAL FLUID"),
        ("FUNGAL CULTURE", "PLEURAL FLUID"),
        ("GRAM STAIN", "PLEURAL FLUID"),
        ("NOCARDIA CULTURE", "PLEURAL FLUID"),
        ("POTASSIUM HYDROXIDE PREPARATION", "PLEURAL FLUID"),
        ("Respiratory Viral Culture", "PLEURAL FLUID"),
        ("VIRAL CULTURE", "PLEURAL FLUID"),
    ],
    "peritoneal_culture": [
        ("ACID FAST CULTURE", "PERITONEAL FLUID"),
        ("ACID FAST SMEAR", "PERITONEAL FLUID"),
        ("ANAEROBIC CULTURE", "PERITONEAL FLUID"),
        ("FLUID CULTURE", "PERITONEAL FLUID"),
        ("FUNGAL CULTURE", "PERITONEAL FLUID"),
        ("Fluid Culture in Bottles", "PERITONEAL FLUID"),
        ("GRAM STAIN", "PERITONEAL FLUID"),
        ("POTASSIUM HYDROXIDE PREPARATION", "PERITONEAL FLUID"),
        ("WOUND CULTURE", "PERITONEAL FLUID"),
    ],
    "joint_fluid_culture": [
        ("ACID FAST CULTURE", "JOINT FLUID"),
        ("ACID FAST CULTURE", "PROSTHETIC JOINT FLUID"),
        ("ACID FAST SMEAR", "JOINT FLUID"),
        ("ACID FAST SMEAR", "PROSTHETIC JOINT FLUID"),
        ("ANAEROBIC CULTURE", "JOINT FLUID"),
        ("Anaerobic culture, Prosthetic Joint Fluid", "PROSTHETIC JOINT FLUID"),
        ("FLUID CULTURE", "JOINT FLUID"),
        ("FLUID CULTURE", "PROSTHETIC JOINT FLUID"),
        ("FUNGAL CULTURE", "JOINT FLUID"),
        ("FUNGAL CULTURE", "PROSTHETIC JOINT FLUID"),
        ("GRAM STAIN", "JOINT FLUID"),
        ("GRAM STAIN", "PROSTHETIC JOINT FLUID"),
        ("POTASSIUM HYDROXIDE PREPARATION", "JOINT FLUID"),
        ("Sonication culture, prosthetic joint", "PROSTHETIC JOINT FLUID"),
    ],
    "fluid_culture": [
        ("ANAEROBIC CULTURE", "BILE"),
        ("ANAEROBIC CULTURE", "DIALYSIS FLUID"),
        ("ANAEROBIC CULTURE", "FLUID RECEIVED IN BLOOD CULTURE BOTTLES"),
        ("FLUID CULTURE", "ABSCESS"),
        ("FLUID CULTURE", "ASPIRATE"),
        ("FLUID CULTURE", "BILE"),
        ("FLUID CULTURE", "DIALYSIS FLUID"),
        ("FLUID CULTURE", "FLUID RECEIVED IN BLOOD CULTURE BOTTLES"),
        ("FLUID CULTURE", "FLUID WOUND"),
        ("FLUID CULTURE", "FLUID,OTHER"),
        ("ISOLATE FOR MIC", "FLUID,OTHER"),
        ("WOUND CULTURE", "BILE"),
    ],
    "bone_marrow_culture": [
        ("ACID FAST CULTURE", "BONE MARROW"),
        ("ACID FAST SMEAR", "BONE MARROW"),
        ("ANAEROBIC CULTURE", "BONE MARROW"),
        ("FLUID CULTURE", "BONE MARROW"),
        ("FUNGAL CULTURE", "BONE MARROW"),
        ("GRAM STAIN", "BONE MARROW"),
        ("POTASSIUM HYDROXIDE PREPARATION", "BONE MARROW"),
    ],
    "csf_culture": [
        ("ACID FAST CULTURE", "CSF;SPINAL FLUID"),
        ("ACID FAST SMEAR", "CSF;SPINAL FLUID"),
        ("ANAEROBIC CULTURE", "CSF;SPINAL FLUID"),
        ("CRYPTOCOCCAL ANTIGEN", "CSF;SPINAL FLUID"),
        ("CRYPTOCOCCAL ANTIGEN", "SEROLOGY/BLOOD"),
        ("Enterovirus Culture", "CSF;SPINAL FLUID"),
        ("FLUID CULTURE", "CSF;SPINAL FLUID"),
        ("FUNGAL CULTURE", "CSF;SPINAL FLUID"),
        ("HIV-1 Viral Load/Ultrasensitive", "CSF;SPINAL FLUID"),
        ("POTASSIUM HYDROXIDE PREPARATION", "CSF;SPINAL FLUID"),
        ("QUANTITATIVE CRYPTOCOCCAL ANTIGEN", "CSF;SPINAL FLUID"),
        ("QUANTITATIVE CRYPTOCOCCAL ANTIGEN", "SEROLOGY/BLOOD"),
        ("VARICELLA-ZOSTER CULTURE", "CSF;SPINAL FLUID"),
        ("VIRAL CULTURE", "CSF;SPINAL FLUID"),
        ("VIRAL CULTURE: R/O HERPES SIMPLEX VIRUS", "CSF;SPINAL FLUID"),
    ],
    "fungal_tissue_wound": [
        ("ACID FAST CULTURE", "ABSCESS"),
        ("ACID FAST CULTURE", "ASPIRATE"),
        ("ACID FAST CULTURE", "BIOPSY"),
        ("ACID FAST CULTURE", "CORNEAL EYE SCRAPINGS"),
        ("ACID FAST CULTURE", "FOOT CULTURE"),
        ("ACID FAST CULTURE", "SWAB"),
        ("ACID FAST CULTURE", "TISSUE"),
        ("ACID FAST SMEAR", "ABSCESS"),
        ("ACID FAST SMEAR", "ASPIRATE"),
        ("ACID FAST SMEAR", "BIOPSY"),
        ("ACID FAST SMEAR", "CORNEAL EYE SCRAPINGS"),
        ("ACID FAST SMEAR", "FOOT CULTURE"),
        ("ACID FAST SMEAR", "SWAB"),
        ("ACID FAST SMEAR", "TISSUE"),
        ("ED Gram Stain for Yeast", "Swab"),
        ("ED Gram Stain for Yeast", "SWAB"),
        ("FUNGAL CULTURE", "ABSCESS"),
        ("FUNGAL CULTURE", "ASPIRATE"),
        ("FUNGAL CULTURE", "BIOPSY"),
        ("FUNGAL CULTURE", "SKIN SCRAPINGS"),
        ("FUNGAL CULTURE", "SWAB"),
        ("FUNGAL CULTURE", "THROAT FOR STREP"),
        ("FUNGAL CULTURE", "TISSUE"),
        ("FUNGAL CULTURE (HAIR/SKIN/NAILS)", "NAIL SCRAPINGS"),
        ("FUNGAL CULTURE (HAIR/SKIN/NAILS)", "SKIN SCRAPINGS"),
        ("Malassezia furfur Culture", "SWAB"),
        ("POTASSIUM HYDROXIDE PREPARATION", "ABSCESS"),
        ("POTASSIUM HYDROXIDE PREPARATION", "ASPIRATE"),
        ("POTASSIUM HYDROXIDE PREPARATION", "BIOPSY"),
        ("POTASSIUM HYDROXIDE PREPARATION", "SWAB"),
        ("POTASSIUM HYDROXIDE PREPARATION", "TISSUE"),
        ("POTASSIUM HYDROXIDE PREPARATION (HAIR/SKIN/NAILS)", "NAIL SCRAPINGS"),
        ("POTASSIUM HYDROXIDE PREPARATION (HAIR/SKIN/NAILS)", "SKIN SCRAPINGS"),
        ("POTASSIUM HYDROXIDE PREPARATION (HAIR/SKIN/NAILS)", "SWAB"),
        ("POTASSIUM HYDROXIDE PREPARATION (HAIR/SKIN/NAILS)", "TISSUE"),
    ],
    "fungal_respiratory": [
        ("FUNGAL CULTURE", "BRONCHIAL BRUSH"),
        ("FUNGAL CULTURE", "BRONCHIAL BRUSH - PROTECTED"),
        ("FUNGAL CULTURE", "BRONCHIAL WASHINGS"),
        ("FUNGAL CULTURE", "BRONCHOALVEOLAR LAVAGE"),
        ("FUNGAL CULTURE", "Mini-BAL"),
        ("FUNGAL CULTURE", "SPUTUM"),
        ("FUNGAL CULTURE", "TRACHEAL ASPIRATE"),
        ("POTASSIUM HYDROXIDE PREPARATION", "BRONCHIAL BRUSH"),
        ("POTASSIUM HYDROXIDE PREPARATION", "BRONCHIAL WASHINGS"),
        ("POTASSIUM HYDROXIDE PREPARATION", "BRONCHOALVEOLAR LAVAGE"),
        ("POTASSIUM HYDROXIDE PREPARATION", "Mini-BAL"),
        ("POTASSIUM HYDROXIDE PREPARATION", "SPUTUM"),
        ("POTASSIUM HYDROXIDE PREPARATION", "TRACHEAL ASPIRATE"),
    ],
    "fungal_fluid": [
        ("ACID FAST CULTURE", "BILE"),
        ("ACID FAST CULTURE", "DIALYSIS FLUID"),
        ("ACID FAST CULTURE", "FLUID,OTHER"),
        ("ACID FAST CULTURE", "URINE"),
        ("ACID FAST SMEAR", "BILE"),
        ("ACID FAST SMEAR", "DIALYSIS FLUID"),
        ("ACID FAST SMEAR", "FLUID,OTHER"),
        ("FUNGAL CULTURE", "BILE"),
        ("FUNGAL CULTURE", "DIALYSIS FLUID"),
        ("FUNGAL CULTURE", "FLUID,OTHER"),
        ("POTASSIUM HYDROXIDE PREPARATION", "BILE"),
        ("POTASSIUM HYDROXIDE PREPARATION", "FLUID,OTHER"),
    ],
    "mrsa_staph_screen": [
        ("MRSA SCREEN", "MRSA SCREEN"),
        ("MRSA SCREEN", "STOOL"),
        ("MRSA SCREEN", "Staph aureus swab"),
        ("MRSA SCREEN", "SWAB"),
        ("Staph aureus Preop PCR", "MRSA SCREEN"),
        ("Staph aureus Preop PCR", "Staph aureus swab"),
        ("Staph aureus Screen", "MRSA SCREEN"),
        ("Staph aureus Screen", "SWAB"),
        ("Staph aureus Screen", "Staph aureus swab"),
    ],
    "resistance_screen": [
        ("CRE/ESBL/AMP-C Screening", "SWAB"),
        ("Carbapenemase Resistant Enterobacteriaceae Screen", "CRE Screen"),
        ("Carbapenemase Resistant Enterobacteriaceae Screen", "SWAB"),
        ("Cipro Resistant Screen", "Cipro Resistant Screen"),
        ("Cipro Resistant Screen", "STOOL"),
        ("ED Gram Stain for Yeast", "Swab R/O Yeast Screen"),
        ("R/O VANCOMYCIN RESISTANT ENTEROCOCCUS", "STOOL"),
        ("R/O VANCOMYCIN RESISTANT ENTEROCOCCUS", "SWAB"),
        ("SWAB- R/O YEAST", "Swab R/O Yeast Screen"),
        ("Swab - R/O Yeast - IC", "Infection Control Yeast"),
    ],
    "cdiff": [
        ("C. difficile PCR", "STOOL"),
        ("C. difficile PCR", "STOOL (RECEIVED IN TRANSPORT SYSTEM)"),
        ("C. difficile Toxin antigen assay", "STOOL"),
        ("C. difficile Toxin antigen assay", "STOOL (RECEIVED IN TRANSPORT SYSTEM)"),
        ("CLOSTRIDIUM DIFFICILE TOXIN A & B TEST", "STOOL"),
        ("CLOSTRIDIUM DIFFICILE TOXIN A & B TEST", "STOOL (RECEIVED IN TRANSPORT SYSTEM)"),
        ("CLOSTRIDIUM DIFFICILE TOXIN ASSAY", "STOOL"),
        ("CLOSTRIDIUM DIFFICILE TOXIN ASSAY", "STOOL (RECEIVED IN TRANSPORT SYSTEM)"),
    ],
    "stool_bacterial": [
        ("CAMPYLOBACTER CULTURE", "FECAL SWAB"),
        ("CAMPYLOBACTER CULTURE", "STOOL"),
        ("CAMPYLOBACTER CULTURE", "STOOL (RECEIVED IN TRANSPORT SYSTEM)"),
        ("FECAL CULTURE", "FECAL SWAB"),
        ("FECAL CULTURE", "STOOL"),
        ("FECAL CULTURE", "STOOL (RECEIVED IN TRANSPORT SYSTEM)"),
        ("FECAL CULTURE - R/O E.COLI 0157:H7", "STOOL"),
        ("FECAL CULTURE - R/O E.COLI 0157:H7", "STOOL (RECEIVED IN TRANSPORT SYSTEM)"),
        ("FECAL CULTURE - R/O VIBRIO", "STOOL"),
        ("FECAL CULTURE - R/O VIBRIO", "STOOL (RECEIVED IN TRANSPORT SYSTEM)"),
        ("FECAL CULTURE - R/O YERSINIA", "STOOL"),
        ("FECAL CULTURE - R/O YERSINIA", "STOOL (RECEIVED IN TRANSPORT SYSTEM)"),
        ("SHIGA TOXIN (EHEC)", "STOOL"),
        ("STOOL SMEAR FOR POLYMORPHONUCLEAR LEUKOCYTES", "STOOL"),
    ],
    "stool_parasitology": [
        ("ACID FAST CULTURE", "STOOL"),
        ("Acid Fast Stain for Cryptosporidium", "ASPIRATE"),
        ("Acid Fast Stain for Cryptosporidium", "STOOL"),
        ("CYCLOSPORA STAIN", "STOOL"),
        ("CYCLOSPORA STAIN", "STOOL (RECEIVED IN TRANSPORT SYSTEM)"),
        ("Concentration and Stain for Giardia", "STOOL"),
        ("Cryptosporidium/Giardia (DFA)", "STOOL"),
        ("Cryptosporidium/Giardia (DFA)", "STOOL (RECEIVED IN TRANSPORT SYSTEM)"),
        ("MICROSPORIDIA STAIN", "ASPIRATE"),
        ("MICROSPORIDIA STAIN", "STOOL"),
        ("MICROSPORIDIA STAIN", "STOOL (RECEIVED IN TRANSPORT SYSTEM)"),
        ("O&P MACROSCOPIC EXAM - ARTHROPOD", "ARTHROPOD"),
        ("O&P MACROSCOPIC EXAM - ARTHROPOD", "STOOL"),
        ("O&P MACROSCOPIC EXAM - WORM", "STOOL"),
        ("O&P MACROSCOPIC EXAM - WORM", "WORM"),
        ("OVA + PARASITES", "BRONCHOALVEOLAR LAVAGE"),
        ("OVA + PARASITES", "SPUTUM"),
        ("OVA + PARASITES", "STOOL"),
        ("OVA + PARASITES", "STOOL (RECEIVED IN TRANSPORT SYSTEM)"),
        ("OVA + PARASITES", "TISSUE"),
        ("OVA + PARASITES", "URINE"),
        ("SCOTCH TAPE PREP/PADDLE", "SCOTCH TAPE PREP/PADDLE"),
        ("VIRAL CULTURE", "STOOL"),
    ],
    "herpesvirus_serology": [
        ("CMV IgG ANTIBODY", "Blood (CMV AB)"),
        ("CMV IgG ANTIBODY", "SEROLOGY/BLOOD"),
        ("CMV IgM ANTIBODY", "Blood (CMV AB)"),
        ("CMV IgM ANTIBODY", "SEROLOGY/BLOOD"),
        ("CMV Viral Load", "IMMUNOLOGY"),
        ("CMV Viral Load", "Immunology (CMV)"),
        ("EPSTEIN-BARR VIRUS EBNA IgG AB", "Blood (EBV)"),
        ("EPSTEIN-BARR VIRUS EBNA IgG AB", "SEROLOGY/BLOOD"),
        ("EPSTEIN-BARR VIRUS VCA-IgG AB", "Blood (EBV)"),
        ("EPSTEIN-BARR VIRUS VCA-IgG AB", "SEROLOGY/BLOOD"),
        ("EPSTEIN-BARR VIRUS VCA-IgM AB", "Blood (EBV)"),
        ("EPSTEIN-BARR VIRUS VCA-IgM AB", "SEROLOGY/BLOOD"),
        ("MONOSPOT", "SEROLOGY/BLOOD"),
        ("VARICELLA-ZOSTER IgG SEROLOGY", "SEROLOGY/BLOOD"),
    ],
    "hepatitis_hiv": [
        ("HBV Viral Load", "IMMUNOLOGY"),
        ("HCV GENOTYPE", "IMMUNOLOGY"),
        ("HCV VIRAL LOAD", "IMMUNOLOGY"),
        ("HIV-1 Viral Load/Ultrasensitive", "IMMUNOLOGY"),
        ("Reflex HCV Qual PCR", "IMMUNOLOGY"),
    ],
    "syphilis_serology": [
        ("QUANTITATIVE RPR", "SEROLOGY/BLOOD"),
        ("RAPID PLASMA REAGIN TEST", "SEROLOGY/BLOOD"),
        ("RPR w/check for Prozone", "SEROLOGY/BLOOD"),
        ("TREPONEMAL ANTIBODY TEST", "SEROLOGY/BLOOD"),
    ],
    "misc_serology": [
        ("ASO Screen", "SEROLOGY/BLOOD"),
        ("ASO TITER", "SEROLOGY/BLOOD"),
        ("HELICOBACTER PYLORI ANTIBODY TEST", "SEROLOGY/BLOOD"),
        ("LYME SEROLOGY", "SEROLOGY/BLOOD"),
        ("Lyme IgG", "Blood (LYME)"),
        ("Lyme IgM", "Blood (LYME)"),
        ("MUMPS IgG ANTIBODY", "SEROLOGY/BLOOD"),
        ("Malaria Antigen Test", "Blood (Malaria)"),
        ("RUBELLA IgG SEROLOGY", "SEROLOGY/BLOOD"),
        ("RUBEOLA ANTIBODY, IgG", "SEROLOGY/BLOOD"),
        ("Rubella IgG/IgM Antibody", "SEROLOGY/BLOOD"),
        ("TOXOPLASMA IgG ANTIBODY", "Blood (Toxo)"),
        ("TOXOPLASMA IgG ANTIBODY", "SEROLOGY/BLOOD"),
        ("TOXOPLASMA IgM ANTIBODY", "Blood (Toxo)"),
        ("TOXOPLASMA IgM ANTIBODY", "SEROLOGY/BLOOD"),
    ],
    "herpesvirus_culture_antigen": [
        ("CYTOMEGALOVIRUS EARLY ANTIGEN TEST (SHELL VIAL METHOD)", "BIOPSY"),
        ("CYTOMEGALOVIRUS EARLY ANTIGEN TEST (SHELL VIAL METHOD)", "TISSUE"),
        ("CYTOMEGALOVIRUS EARLY ANTIGEN TEST (SHELL VIAL METHOD)", "VIRAL CULTURE: R/O CYTOMEGALOVIRUS"),
        ("DIRECT ANTIGEN TEST FOR VARICELLA-ZOSTER VIRUS", "DIRECT ANTIGEN TEST FOR VARICELLA-ZOSTER VIRUS"),
        ("DIRECT ANTIGEN TEST FOR VARICELLA-ZOSTER VIRUS", "Direct Antigen Test for Herpes Simplex Virus Types 1 & 2"),
        ("DIRECT ANTIGEN TEST FOR VARICELLA-ZOSTER VIRUS", "SWAB"),
        ("Direct Antigen Test for Herpes Simplex Virus Types 1 & 2", "DIRECT ANTIGEN TEST FOR VARICELLA-ZOSTER VIRUS"),
        ("Direct Antigen Test for Herpes Simplex Virus Types 1 & 2", "Direct Antigen Test for Herpes Simplex Virus Types 1 & 2"),
        ("Direct Antigen Test for Herpes Simplex Virus Types 1 & 2", "SKIN SCRAPINGS"),
        ("Direct Antigen Test for Herpes Simplex Virus Types 1 & 2", "SWAB"),
        ("Direct Antigen Test for Herpes Simplex Virus Types 1 & 2", "VIRAL CULTURE:R/O HERPES SIMPLEX VIRUS"),
        ("VARICELLA-ZOSTER CULTURE", "Direct Antigen Test for Herpes Simplex Virus Types 1 & 2"),
        ("VARICELLA-ZOSTER CULTURE", "SKIN SCRAPINGS"),
        ("VARICELLA-ZOSTER CULTURE", "SWAB"),
        ("VARICELLA-ZOSTER CULTURE", "THROAT CULTURE"),
        ("VARICELLA-ZOSTER CULTURE", "TISSUE"),
        ("VARICELLA-ZOSTER CULTURE", "VARICELLA-ZOSTER CULTURE"),
        ("VARICELLA-ZOSTER CULTURE", "VIRAL CULTURE:R/O HERPES SIMPLEX VIRUS"),
        ("VIRAL CULTURE", "ASPIRATE"),
        ("VIRAL CULTURE", "BIOPSY"),
        ("VIRAL CULTURE", "FLUID,OTHER"),
        ("VIRAL CULTURE", "STOOL (RECEIVED IN TRANSPORT SYSTEM)"),
        ("VIRAL CULTURE", "SWAB"),
        ("VIRAL CULTURE", "THROAT CULTURE"),
        ("VIRAL CULTURE", "THROAT FOR STREP"),
        ("VIRAL CULTURE", "TISSUE"),
        ("VIRAL CULTURE", "VIRAL CULTURE"),
        ("VIRAL CULTURE: R/O CYTOMEGALOVIRUS", "BIOPSY"),
        ("VIRAL CULTURE: R/O CYTOMEGALOVIRUS", "SWAB"),
        ("VIRAL CULTURE: R/O CYTOMEGALOVIRUS", "TISSUE"),
        ("VIRAL CULTURE: R/O CYTOMEGALOVIRUS", "VIRAL CULTURE: R/O CYTOMEGALOVIRUS"),
        ("VIRAL CULTURE: R/O CYTOMEGALOVIRUS", "VIRAL CULTURE:R/O HERPES SIMPLEX VIRUS"),
        ("VIRAL CULTURE: R/O HERPES SIMPLEX VIRUS", "BIOPSY"),
        ("VIRAL CULTURE: R/O HERPES SIMPLEX VIRUS", "Direct Antigen Test for Herpes Simplex Virus Types 1 & 2"),
        ("VIRAL CULTURE: R/O HERPES SIMPLEX VIRUS", "SKIN SCRAPINGS"),
        ("VIRAL CULTURE: R/O HERPES SIMPLEX VIRUS", "STOOL"),
        ("VIRAL CULTURE: R/O HERPES SIMPLEX VIRUS", "SWAB"),
        ("VIRAL CULTURE: R/O HERPES SIMPLEX VIRUS", "THROAT CULTURE"),
        ("VIRAL CULTURE: R/O HERPES SIMPLEX VIRUS", "THROAT FOR STREP"),
        ("VIRAL CULTURE: R/O HERPES SIMPLEX VIRUS", "TISSUE"),
        ("VIRAL CULTURE: R/O HERPES SIMPLEX VIRUS", "VIRAL CULTURE: R/O CYTOMEGALOVIRUS"),
        ("VIRAL CULTURE: R/O HERPES SIMPLEX VIRUS", "VIRAL CULTURE:R/O HERPES SIMPLEX VIRUS"),
    ],
    "gc_chlamydia_sti": [
        ("CHLAMYDIA CULTURE", "SWAB"),
        ("Chlamydia trachomatis, Nucleic Acid Probe, with Amplification", "SWAB"),
        ("Chlamydia trachomatis, Nucleic Acid Probe, with Amplification", "URINE"),
        ("GENITAL CULTURE", "SWAB"),
        ("GENITAL CULTURE FOR TOXIC SHOCK", "SWAB"),
        ("NEISSERIA GONORRHOEAE (GC), NUCLEIC ACID PROBE, WITH AMPLIFICATION", "SWAB"),
        ("NEISSERIA GONORRHOEAE (GC), NUCLEIC ACID PROBE, WITH AMPLIFICATION", "URINE"),
        ("R/O GC Only", "RECTAL - R/O GC"),
        ("R/O GC Only", "SWAB"),
        ("R/O GC Only", "SWAB, R/O GC"),
        ("R/O GC Only", "THROAT"),
        ("R/O GC Only", "THROAT CULTURE"),
        ("R/O GC Only", "THROAT FOR STREP"),
    ],
    "vaginal_genital_flora": [
        ("R/O GROUP B BETA STREP", "ANORECTAL/VAGINAL"),
        ("R/O GROUP B BETA STREP", "SWAB"),
        ("R/O Group B Strep - Penicillin Allergy", "ANORECTAL/VAGINAL"),
        ("R/O Group B Strep - Penicillin Allergy", "SWAB"),
        ("SMEAR FOR BACTERIAL VAGINOSIS", "ANORECTAL/VAGINAL"),
        ("SMEAR FOR BACTERIAL VAGINOSIS", "SWAB"),
        ("SMEAR FOR BACTERIAL VAGINOSIS", "Swab"),
        ("TRICHOMONAS SALINE PREP", "SWAB"),
        ("TRICHOMONAS SALINE PREP", "URINE"),
        ("YEAST VAGINITIS CULTURE", "ANORECTAL/VAGINAL"),
        ("YEAST VAGINITIS CULTURE", "SWAB"),
    ],
    "throat_strep": [
        ("GRAM STAIN- R/O THRUSH", "SWAB"),
        ("GRAM STAIN- R/O THRUSH", "THROAT CULTURE"),
        ("GRAM STAIN- R/O THRUSH", "THROAT FOR STREP"),
        ("R/O Beta Strep Group A", "SWAB"),
        ("R/O Beta Strep Group A", "THROAT"),
        ("R/O Beta Strep Group A", "THROAT CULTURE"),
        ("R/O Beta Strep Group A", "THROAT FOR STREP"),
    ],
}

EXCLUDED_SPEC_TYPES = [
    "POSTMORTEM CULTURE",
    "BLOOD CULTURE (POST-MORTEM)",
    "BONE MARROW - CYTOGENETICS",
    "AMNIOTIC FLUID",
    "CHORIONIC VILLUS SAMPLE",
    "NEOPLASTIC BLOOD",
    "MICRO PROBLEM PATIENT",
    "Touch Prep/Sections",
]

EXCLUDED_TESTS = [
    "ADDITIONAL CELLS COUNTED",
    "Additional Cells and Karyotype",
    "Blood Culture, Post Mortem",
    "CHROMOSOME ANALYSIS - ADDITIONAL KARYOTYPE",
    "CHROMOSOME ANALYSIS-AMNIOTIC FLUID",
    "CHROMOSOME ANALYSIS-BLOOD",
    "CHROMOSOME ANALYSIS-BONE MARROW",
    "CHROMOSOME ANALYSIS-CVS",
    "CHROMOSOME ANALYSIS-FLUID",
    "CHROMOSOME ANALYSIS-NEOPLASTIC BLOOD",
    "CHROMOSOME ANALYSIS-TISSUE",
    "CVS NEEDLE ASPIRATION EVALUATION",
    "Cryopreservation - Cells",
    "Deparaffinization, Lysis of Cells",
    "FISH ANALYSIS, 10-30 CELLS",
    "FISH ANALYSIS, 3-5 CELLS",
    "FOCUSED ANALYSIS",
    "INTERPHASE FISH ANALYSIS, 100-300 CELLS",
    "INTERPHASE FISH ANALYSIS, 25-99 CELLS",
    "MOLECULAR CYTOGENETICS - DNA PROBE",
    "MOLECULAR CYTOGENETICS-DNA Probe",
    "POST MORTEM MYCOLOGY CULTURE",
    "POST-MORTEM ACID-FAST CULTURE",
    "POST-MORTEM DIRECT ACID-FAST STAIN",
    "POST-MORTEM VIRAL CULTURE",
    "POSTMORTEM CULTURE",
    "Problem",
    "Stool Hold Request",
    "TISSUE CULTURE-AMNIOTIC FLUID",
    "TISSUE CULTURE-CVS",
    "TISSUE CULTURE-FLUID",
    "TISSUE CULTURE-LYMPHOCYTE",
    "Tissue Culture - Neoplastic Blood",
    "Tissue Culture-Bone Marrow",
    "Tissue culture for additional cells",
    "voided",
]

_COMMENT_CLEANING = {
    "max_sentences": 2,
    "max_chars": 200,
    "discard_prefixes": [
        "TEST CANCELLED",
        "PATIENT CREDITED",
        "Patient credited",
        "Test cancelled",
        "test cancelled",
        "TEST NOT PERFORMED",
        "DUPLICATE ORDER",
        "GRAM STAIN OF THIS SPECIMEN INDICATES CONTAMINATION",
    ],
    "strip_triggers": [
        "Reference Range",
        "Reference range",
        "Detection Range",
        "Detection range",
        "Linear range",
        "Performed by",
        "performed by",
        "Performed using",
        "performed using",
        "Validated for use",
        "validated for use",
        "Performance characteristics",
        "performance characteristics",
        "A positive IgG result",
        "A positive IgM result",
        "This test",
        "this test",
        "In most population",
        "The FDA",
        "the FDA",
        "screened for",
        "Detection of viruses",
        "PLEASE SUBMIT ANOTHER",
        "rule out",
        "approved",
        "Patients",
        "patients",
    ],
}


def run(config: dict) -> None:
    _check_required_keys(config, ["CLASSIFICATIONS_DIR"])

    classifications_dir = str(config["CLASSIFICATIONS_DIR"])
    registry_path = config.get("HASH_REGISTRY_PATH", "")
    output_path = os.path.join(classifications_dir, "micro_panel_config.yaml")

    if registry_path and not config.get("FORCE_RERUN", False):
        if os.path.exists(output_path):
            logger.info(
                "micro_panel_config.yaml already exists — skipping (use FORCE_RERUN to rebuild)."
            )
            return

    panels = {
        panel_name: {
            "description": f"Microbiology panel: {panel_name.replace('_', ' ')}",
            "combos": [list(combo) for combo in combos]
        }
        for panel_name, combos in PANELS_37.items()
    }
    config_data = {
        "panels": panels,
        "excluded_tests": EXCLUDED_TESTS,
        "excluded_spec_types": EXCLUDED_SPEC_TYPES,
        "comment_cleaning": _COMMENT_CLEANING,
    }

    os.makedirs(classifications_dir, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as fh:
        yaml.dump(config_data, fh, allow_unicode=True, sort_keys=False)

    total_combos = sum(len(v["combos"]) for v in panels.values())
    logger.info(
        "Wrote micro_panel_config.yaml: %d panels, %d total combos → %s",
        len(panels),
        total_combos,
        output_path,
    )
